name: Ruby

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby version specified in `.ruby-version`
      uses: eregon/use-ruby-action@master

    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Setup cache key and directory for gems cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}

    - name: Install dependencies
      run:  bundle install --jobs 4 --retry 3

    - name: Run migrations
      env:
        RAILS_ENV: test
        RUBYOPT: -W0
      run: |
        cp config/database.yml.github config/database.yml
        bundle exec rails db:reset db:setup db:migrate

    - name: Run Rubocop
      env:
        RAILS_ENV: test
        RUBYOPT: -W0
      run: bundle exec rubocop --config .rubocop.yml

    - name: Run tests with RSpec
      env:
        RAILS_ENV: test
        RUBYOPT: -W0
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        DEVISE_JWT_SECRET_KEY: ${{ secrets.DEVISE_JWT_SECRET_KEY }}
      run: bundle exec rspec
